language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "abbinav-github"
    token:
      secure: "c10b556cfb06695d5be54486aae08795502a20d9"

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'